lr_backbone: 0.00001
lr: 0.0001
num_epochs: 30
lr_drop: 20
start_epoch: 0
weight_decay: 0.0001
backbone: 'resnet101'
position_embedding: 'sine'
dilation: True
batch_size: 32
num_workers: 1
checkpoint: 'artifacts/train/model_9.pth'
clip_max_norm: 0.1
hidden_dim: 256
pad_token_id: 0
max_length: 128
dropout: 0.1
vocab_size: 30522
enc_layers: 6
dec_layers: 6
dim_feed_forward: 2048
nheads: 8
pre_norm: True
